{!! file_get_contents(base_path('docs/api-references/api.md')) !!}
{!! file_get_contents(base_path('docs/api-references/login.md')) !!}
{!! file_get_contents(base_path('docs/api-references/register.md')) !!}
{!! file_get_contents(base_path('docs/api-references/book.md')) !!}
{!! file_get_contents(base_path('docs/api-references/category.md')) !!}
{!! file_get_contents(base_path('docs/api-references/post.md')) !!}
{!! file_get_contents(base_path('docs/api-references/borrow.md')) !!}
{!! file_get_contents(base_path('docs/api-references/profile.md')) !!}
{!! file_get_contents(base_path('docs/api-references/reset_password.md')) !!}
{!! file_get_contents(base_path('docs/api-references/favorite.md')) !!}
